[package]
name = "custom-element"
version = "0.1.4"
edition = "2021"
license = "MIT OR Apache-2.0"
keywords = ["web-components", "custom-elements", "html", "web-assembly"]
categories = ["web-programming", "wasm", "gui"]
description = "A CustomElement trait for implementing custom elements (web components) in Rust"
repository = "https://github.com/austintheriot/custom-element"
readme = "README.md"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
web-sys = { version = "0.3.70", features = [
	"Window",
	"Event",
	"Document",
	"HtmlElement",
] }
js-sys = "0.3.70"
wasm-bindgen = "=0.2.100"

[dev-dependencies]
getrandom = { version = "0.2.14", features = ["js"] }
rand = { version = "0.8.5" }
wasm-bindgen-test = "0.3"
web-sys = { version = "0.3.70", features = [
	"CustomElementRegistry",
	"ElementDefinitionOptions",
] }
